name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@24.20.0
          cache: true

      - name: Publish
        run: pnpm publish --no-git-checks

      - name: Generate changelog
        run: pnpm exec changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
